'use strict';

// showing status messages to the user
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const ANY_FETCH_START = 'ANY_FETCH_START';
export const ANY_FETCH_END = 'ANY_FETCH_END';

//auth user interactions
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// users
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

//questions
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const SELECT_QUESTION = 'SELECT_QUESTION';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const MAKE_PRESENT_SUCCESS = 'MAKE_PRESENT_SUCCESS';
export const CLOSE_QUESTION_SUCCESS = 'CLOSE_QUESTION_SUCCESS'
